#
# Static definition of "discoverable-client" as "staticclient"
#
# This file provides static API service definition in YAML format.
# It is loaded by the Discovery Service during its startup.
#
services:
    - serviceId: gateway  # unique lowercase ID of the service
      catalogUiTileId: static  # ID of the API Catalog UI tile (visual grouping of the services)
      title: Statically Defined API Service  # Title of the service in the API catalog
      description: Sample to demonstrate how to add an API service with Swagger to API Catalog using a static YAML definition  # Description of the service in the API catalog
      instanceBaseUrls:  # list of base URLs for each instance
        - https://localhost:10010/  # scheme://hostname:port/contextPath
      homePageRelativeUrl: / # Normally used for informational purposes for other services to use it as a landing page
      statusPageRelativeUrl: /application/info  # Appended to the instanceBaseUrl
      healthCheckRelativeUrl: /application/health  # Appended to the instanceBaseUrl
      routes:
        - gatewayUrl: api/v1  # [api/ui/ws]/v{majorVersion}
          serviceRelativeUrl: /api/v1 # relativePath that is added to baseUrl of an instance
        - gatewayUrl: ui/v1
          serviceRelativeUrl: /
        - gatewayUrl: ws/v1
          serviceRelativeUrl: /ws
      # List of APIs provided by the service (currently only one is supported):
      apiInfo:
        - apiId: zowe.apiml.gatewayservice1
          gatewayUrl: api/v1
          swaggerUrl: https://localhost:10012/discoverableclient/v2/api-docs
      customMetadata:
            apiml:
                okToRetryOnAllOperations: true

    - serviceId: gateway  # unique lowercase ID of the service
      catalogUiTileId: static  # ID of the API Catalog UI tile (visual grouping of the services)
      title: Statically Defined API Service  # Title of the service in the API catalog
      description: Sample to demonstrate how to add an API service with Swagger to API Catalog using a static YAML definition  # Description of the service in the API catalog
      instanceBaseUrls:  # list of base URLs for each instance
          - https://localhost:10020/  # scheme://hostname:port/contextPath
      homePageRelativeUrl: / # Normally used for informational purposes for other services to use it as a landing page
      statusPageRelativeUrl: /application/info  # Appended to the instanceBaseUrl
      healthCheckRelativeUrl: /application/health  # Appended to the instanceBaseUrl
      routes:
          - gatewayUrl: api/v1  # [api/ui/ws]/v{majorVersion}
            serviceRelativeUrl: /api/v1 # relativePath that is added to baseUrl of an instance
          - gatewayUrl: ui/v1
            serviceRelativeUrl: /
          - gatewayUrl: ws/v1
            serviceRelativeUrl: /ws
        # List of APIs provided by the service (currently only one is supported):
      apiInfo:
          - apiId: zowe.apiml.gatewayservice2
            gatewayUrl: api/v1
            swaggerUrl: https://localhost:10010/gateway/v2/api-docs
      customMetadata:
          apiml:
              okToRetryOnAllOperations: true

    - serviceId: gateway1  # unique lowercase ID of the service
      catalogUiTileId: static  # ID of the API Catalog UI tile (visual grouping of the services)
      title: Statically Defined API Service  # Title of the service in the API catalog
      description: Sample to demonstrate how to add an API service with Swagger to API Catalog using a static YAML definition  # Description of the service in the API catalog
      instanceBaseUrls:  # list of base URLs for each instance
          - https://localhost:10030/  # scheme://hostname:port/contextPath
      homePageRelativeUrl: / # Normally used for informational purposes for other services to use it as a landing page
      statusPageRelativeUrl: /application/info  # Appended to the instanceBaseUrl
      healthCheckRelativeUrl: /application/health  # Appended to the instanceBaseUrl
      routes:
          - gatewayUrl: api/v1  # [api/ui/ws]/v{majorVersion}
            serviceRelativeUrl: /api/v1 # relativePath that is added to baseUrl of an instance
          - gatewayUrl: ui/v1
            serviceRelativeUrl: /
          - gatewayUrl: ws/v1
            serviceRelativeUrl: /ws
        # List of APIs provided by the service (currently only one is supported):
      apiInfo:
          - apiId: zowe.apiml.gatewayservice
            gatewayUrl: api/v1
            version: 1.0.0
