#
# Static definition for z/OSMF
#
# To skip adding service certificate or CA certificate to the truststore
# of the API Gateway you need to see following setting in the
# config/local/gateway-service.yml:
#
#   apiml:
#       security:
#           verifySslCertificatesOfServices: false
#
#  Then you can access z/OSMF via the API gateway:
#
#   http --verify=keystore/local_ca/localca.cer GET https://localhost:10010/api/{zosmf-service-id}/zosmf/info 'X-CSRF-ZOSMF-HEADER;'
#
services:
    - serviceId: ibmzosmf  # unique lowercase ID of the service #WAS: zosmfca32
      title: IBM z/OSMF on CA32
      description: IBM z/OS Management Facility REST API service on CA32
      catalogUiTileId: zosmf
      instanceBaseUrls:  # list of base URLs for each instance
        - https://usilca32.lvn.broadcom.net:1443/  # scheme://hostname:port/contextPath/
      homePageRelativeUrl:  # Home page is at the same URL
      routedServices:
        - gatewayUrl: api  # [api/ui/ws]/v{majorVersion}
          serviceRelativeUrl:
        - gatewayUrl: ui
          serviceRelativeUrl:
      apiInfo:
        - apiId: com.ibm.zosmf
          gatewayUrl: api
          version: 2.3.0
          documentationUrl: https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.3.0/com.ibm.zos.v2r3.izua700/IZUHPINFO_RESTServices.htm
    - serviceId: zosmfzowe  # unique lowercase ID of the service
      title: IBM z/OSMF on river.zowe
      description: IBM z/OS Management Facility REST API service on CA32
      catalogUiTileId: zosmf
      instanceBaseUrls:  # list of base URLs for each instance
        - https://river.zowe.org:50018  # scheme://hostname:port/contextPath/
      homePageRelativeUrl:  # Home page is at the same URL
      routedServices:
        - gatewayUrl: api  # [api/ui/ws]/v{majorVersion}
          serviceRelativeUrl:
        - gatewayUrl: ui
          serviceRelativeUrl:
      apiInfo:
        - apiId: com.ibm.zosmf
          gatewayUrl: api
          version: 2.3.0
          documentationUrl: https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.3.0/com.ibm.zos.v2r3.izua700/IZUHPINFO_RESTServices.htm

catalogUiTiles:
    zosmf:
        title: IBM z/OSMF API Services
        description: IBM z/OS Management Facility REST API services
