spring.profiles.include: diag,debug
apiml:
    service:
        hostname: localhost
        ipAddress: 127.0.0.1
        port: 10010
        discoveryServiceUrls: https://localhost:10011/eureka/
    security:
        allowTokenRefresh: true
        webfinger:
            fileLocation: config/local/webfinger.yml
        personalAccessToken:
            enabled: false
        oidc:
            enabled: false
            clientId:
            clientSecret:
            introspectUrl:
            registry:
            identityMapperUrl:
            identityMapperUser:
        auth:
            jwt:
                customAuthHeader:
            passticket:
                customUserHeader:
                customAuthHeader:
            provider: zosmf
            zosmf:
                serviceId: ibmzosmf  # Replace me with the correct z/OSMF service id
                usePassTicketForBasicAuth: true  # Use passtickets instead of username and password to always get unique zOSMF JWT token
                skipSafPreAuthentication: true   # Set to true for local development environment only!
        ssl:
            verifySslCertificatesOfServices: true
        x509:
            enabled: true
    banner: console

spring:
    config:
        use-legacy-processing: true
    output:
        ansi:
            enabled: always
    cache:
        ehcache:
            config: classpath:ehcache.xml

server:
    internal:
        enabled: true
        port: 10017
        ssl:
            keyAlias: localhost-multi
            keyStore: keystore/localhost/localhost-multi.keystore.p12
    ssl:
        keyAlias: localhost
        keyPassword: password
        keyStore: keystore/localhost/localhost.keystore.p12
        keyStorePassword: password
        keyStoreType: PKCS12
        trustStore: keystore/localhost/localhost.truststore.p12
        trustStorePassword: password
        trustStoreType: PKCS12

---
spring:
    profiles: attls

apiml:
    service:
        scheme: http
        discoveryServiceUrls: http://localhost:10011/eureka/
    security:
        saf:
            urls:
                authenticate: http://localhost:10013/zss/saf/authenticate
                verify: http://localhost:10013/zss/saf/verify


