spring:
    application:
        name: ${apiml.service.serviceId}

    output:
        ansi:
            enabled: always

    profiles:
        include: 'apiml'

logging:
    level:
        ROOT: INFO
        org.springframework: INFO
        org.apache: DEBUG
        org.zowe.apiml: DEBUG

management:
    context-path: /application

server:
    port: ${apiml.service.port}
    context-path: ${apiml.service.contextPath}

    ssl:
        enabled: true
        protocol: TLSv1.2
        enabled-protocols: TLSv1.2,TLSv1.3
        ciphers: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384,TLS_AES_128_GCM_SHA256,TLS_AES_256_GCM_SHA384
        keyStoreType: PKCS12
        trustStoreType: PKCS12

        keyAlias: localhost
        keyPassword: password
        keyStore: keystore/localhost/localhost.keystore.p12
        keyStorePassword: password
        trustStore: keystore/localhost/localhost.truststore.p12
        trustStorePassword: password
