server:
    port: 9090
    ssl:
        enabled: true
        clientAuth: want
        protocol: TLSv1.2
        enabled-protocols: TLSv1.2
        ciphers: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384

        keyAlias: localhost
        keyPassword: password
        keyStore: keystore/localhost/localhost.keystore.p12
        keyStorePassword: password
        keyStoreType: PKCS12
        trustStore: keystore/localhost/localhost.truststore.p12
        trustStorePassword: password
        trustStoreType: PKCS12


spring:
    application:
        name: sc-gateway


# Effective but not needed
#    cloud:
#        gateway:
#            filter:
#                remove-hop-by-hop:
#                    headers: connection, keep-alive, transfer-encoding,  te ,  trailer ,  proxy-authorization ,  proxy-authenticate ,  x-application-context ,  upgrade ,  X-TLS-CLIENT-CERT

#    cloud:
#        gateway:
#            discovery:
#                locator: #configures the discovery client route locator
#                    # disable because custom route locator implemented
#                    enabled: false # Enable RouteLocator to take from DiscoveryClient compliant registry (Eureka) this one is for
#                    #autoconfiguring bean
#                    #the rest is for the copied RouteLocator and I hjacked the config object

#This makes the http client trust everything
#    cloud:
#        gateway:
#            httpclient:
#                ssl:
#                    useInsecureTrustManager: true

#Actuator endpoints under /actuator context to differentiate from Gateway


management:
    endpoint:
        gateway:
            enabled: true # default value
    endpoints:
        web:
            exposure:
                include: '*'
