name: Containers - Build, Test

on:
    push:
        branches: [ v2.x.x ]
        paths-ignore:
            - '**.md'
    pull_request:
        branches: [ v2.x.x ]
        paths-ignore:
            - '**.md'
    workflow_dispatch:

env:
    JOB_ID: ${{ github.run_id }}-${{ github.run_number }}

jobs:

    E2EUITests:
        runs-on: ubuntu-latest
        container: cypress/browsers:latest
        timeout-minutes: 15

        services:
            api-catalog-services:
                image: ghcr.io/balhar-jakub/api-catalog-services:3758098958-3673
                volumes:
                    - /api-defs:/api-defs
            discoverable-client:
                image: ghcr.io/balhar-jakub/discoverable-client:3758098958-3673
            discovery-service:
                image: ghcr.io/balhar-jakub/discovery-service:3758098958-3673
                volumes:
                    - /api-defs:/api-defs
            gateway-service:
                image: ghcr.io/balhar-jakub/gateway-service:3758098958-3673
            mock-services:
                image: ghcr.io/balhar-jakub/mock-services:3758098958-3673

        steps:
            -   uses: actions/checkout@v3
                with:
                    ref: ${{ github.head_ref }}
            -   uses: ./.github/actions/setup
            -   name: Install npm dependencies
                uses: bahmutov/npm-install@v1
                with:
                    working-directory: api-catalog-ui/frontend
            -   name: Cache NPM and Cypress 📦
                uses: actions/cache@v2
                with:
                    path: |
                        ~/.cache/Cypress
                        node_modules
                    key: my-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
            -   name: Cypress run
                run: |
                    cd api-catalog-ui/frontend
                    npm run cy:e2e:ci
            -   name: Upload screenshots
                uses: actions/upload-artifact@v2
                if: failure()
                with:
                    name: cypress-snapshots
                    path: api-catalog-ui/frontend/cypress/screenshots
            -   uses: ./.github/actions/teardown
